### ISSUE TITLE
Add support for Driver API

### ISSUE THREAD

**Issue by dustinwhittle** [orijtech/uber#49]
Can you add support for the Uber Driver APIs? Here is an [example diff from the python sdk](https://github.com/uber/rides-python-sdk/pull/45/files#diff-f28d240a7be85035693dfe494cc123c6).

**Comment by odeke-em** [comment]
Thanks for the request @dustinwhittle! Sounds like a plan, and coincidentally last night before bed, I was reading through the docs at https://developer.uber.com/docs/drivers/introduction so it's cool to see it implemented for Python. I'll work on this.

**Comment by odeke-em** [comment]
Alright, so the progress of methods:
- [X] GetDriverProfile implemented by PR https://github.com/orijtech/uber/pull/50
- [X] List driver payments implemented by PR https://github.com/orijtech/uber/pull/51
- [  ] List driver trips -- unimplemented

**Comment by odeke-em** [comment]
And with all those methods implemented, that concludes the implementation of the new API!!
Now I'll wait on my API being given full access and then run each example and test again.

Thank you @dustinwhittle for requesting for this!

**Comment by dustinwhittle** [comment]
Awesome, thanks!

**Comment by odeke-em** [comment]
Cheers 🍻
